# Generated by Django 3.2.9 on 2022-05-12 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Billing Title')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Billing SubTitle')),
                ('price', models.FloatField(default=0.0, help_text='Membership Price', verbose_name='Billing Price')),
                ('billing_expiry_days', models.IntegerField(default=30, help_text='Billing For x days..')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Billing Description')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
            },
        ),
    ]
